apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mxknrhh4w-go 
  janus-idp.io/tekton: mxknrhh4w-go
  backstage.io/kubernetes-id: mxknrhh4w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mxknrhh4w-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml